# Generated by Django 4.2.1 on 2023-06-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "name",
                    models.CharField(max_length=127, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("possession", models.DecimalField(decimal_places=8, max_digits=28)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(max_length=127, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=127, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("mail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                (
                    "contact_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_relationship",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("total", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "paid",
                    models.DecimalField(
                        decimal_places=8,
                        default=models.DecimalField(decimal_places=8, max_digits=28),
                        max_digits=28,
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "branch_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.CharField(max_length=127, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=127, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("mail", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "loan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.loan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("balance", models.DecimalField(decimal_places=8, max_digits=28)),
                ("reg_date", models.DateTimeField(blank=True, null=True)),
                ("interest_rate", models.DecimalField(decimal_places=8, max_digits=28)),
                ("currency_type", models.CharField(max_length=255)),
                (
                    "staff_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="client_loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.client"
                    ),
                ),
                (
                    "loan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.loan"
                    ),
                ),
            ],
            options={"unique_together": {("client_id", "loan_id")},},
        ),
        migrations.CreateModel(
            name="client_account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.account"
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.client"
                    ),
                ),
            ],
            options={"unique_together": {("client_id", "account_id")},},
        ),
    ]
