# Generated by Django 4.2.1 on 2023-06-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.account",
                    ),
                ),
                (
                    "branch_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.branch"
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.client"
                    ),
                ),
            ],
            options={"unique_together": {("client_id", "branch_name")},},
        ),
        migrations.DeleteModel(name="client_account",),
    ]
