# Generated by Django 4.2.1 on 2023-06-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_reg_date_account_register_date"),
    ]

    operations = [
        migrations.RenameField(model_name="loan", old_name="paid", new_name="balance",),
        migrations.RemoveField(model_name="loan", name="status",),
        migrations.AddField(
            model_name="loan",
            name="staff_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.staff",
            ),
        ),
        migrations.DeleteModel(name="Pay",),
    ]
