# Generated by Django 4.2.1 on 2023-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_loan_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_loan",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
