# Generated by Django 4.2.1 on 2023-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.CharField(max_length=127, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.CharField(max_length=127, primary_key=True, serialize=False),
        ),
    ]
