# Generated by Django 4.2.1 on 2023-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=127, primary_key=True, serialize=False),
                ),
                ("passwd", models.CharField(max_length=127)),
            ],
        ),
    ]
